server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # \u5F00\u542F\u4ECE\u6CE8\u518C\u4E2D\u5FC3\u52A8\u6001\u521B\u5EFA\u8DEF\u7531\u7684\u529F\u80FD\uFF0C\u5229\u7528\u5FAE\u670D\u52A1\u540D\u8FDB\u884C\u8DEF\u7531
      routes:
        - id: payment_routh # \u8DEF\u7531ID\uFF0C\u6CA1\u6709\u56FA\u5B9A\u89C4\u5219\u4F46\u8981\u6C42\u552F\u4E00
          uri: lb://cloud-payment-service #\u5339\u914D\u540E\u63D0\u4F9B\u670D\u52A1\u7684\u8DEF\u7531\u5730\u5740
          predicates:
            - Path=/payment/get/**  #\u65AD\u8A00\uFF0C\u8DEF\u5F84\u76F8\u5339\u914D\u7684\u8FDB\u884C\u8DEF\u7531

        - id: payment_routh2
          uri: lb://cloud-payment-service # \u5339\u914D\u540E\u63D0\u4F9B\u670D\u52A1\u7684\u8DEF\u7531\u5730\u5740
          predicates:
            - Path=/payment/lb/**
            - After=2020-08-11T20:22:58.816+08:00[Australia/Perth]  # \u6307\u5B9A\u65F6\u95F4\u540E\u89E6\u53D1\uFF0C\u76F8\u4F3C\u7684\u8FD8\u6709Before\u548CBetween
#            - Cookie=username, zzyy
#            - Header=X-Request-Id, \d+  #\u8BF7\u6C42\u5934\u8981\u6709\u8BE5\u5C5E\u6027\u5E76\u4E14\u503C\u4E3A\u6574\u6570\u7684\u6B63\u5219\u8868\u8FBE\u5F0F
#            - Method=GET

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka8003.com:8003/eureka, http://eureka8004.com:8004/eureka
